### ISSUE TITLE
Skipping in now playing

### ISSUE THREAD

**Issue by Rexpert** [andytan0727/shuffler#4]
Hi Andy, I found an issue regarding the Now Playing sequence. When I delete a song that arranged before the current playing song, **during playing the song**, the current playing song will skip to next song in the Now Playing sequence without giving signal. Please fix.

**Comment by andytan0727** [comment]
@Rexpert sure. I will find some time to take a look on that issue.

**Comment by Rexpert** [comment]
@andytan0727 Can I follow up on this issue?

**Comment by Rexpert** [comment]
Seems like a duplicate of issue #5
